jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword
          }}
      name: Build with Gradle
      run: 'echo ''org.gradle.caching=true'' >> gradle.properties

        echo ''org.gradle.parallel=true'' >> gradle.properties

        echo ''org.gradle.vfs.watch=true'' >> gradle.properties

        echo ''org.gradle.jvmargs=-Xmx2048m'' >> gradle.properties

        echo ''android.native.buildOutput=verbose'' >> gradle.properties

        ./gradlew publishToMavenLocal

        ./gradlew --stop

        '
    - continue-on-error: true
      name: Upload library
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-library
        path: ~/.m2
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
  test:
    name: Test on API ${{ matrix.api-level }} ${{ matrix.arch }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Enable KVM group perms
      run: 'echo ''KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"''
        | sudo tee /etc/udev/rules.d/99-kvm4all.rules

        sudo udevadm control --reload-rules

        sudo udevadm trigger --name-match=kvm

        '
    - continue-on-error: true
      name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: ${{ matrix.arch }}
        disable-animations: true
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio
          -no-boot-anim -camera-back none
        force-avd-creation: false
        script: ./gradlew connectedCheck
        target: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - api-level: 28
          arch: x86_64
          target: default
        - api-level: 28
          arch: x86
          target: default
        - api-level: 29
          arch: x86_64
          target: default
        - api-level: 29
          arch: x86
          target: default
        - api-level: 30
          arch: x86_64
          target: aosp_atd
        - api-level: 30
          arch: x86
          target: google_apis
        - api-level: 31
          arch: x86_64
          target: aosp_atd
        - api-level: 31
          arch: x86
          target: android-tv
        - api-level: 32
          arch: x86_64
          target: aosp_atd
        - api-level: 33
          arch: x86_64
          target: aosp_atd
        - api-level: 33
          arch: x86
          target: android-tv
        - api-level: 34
          arch: x86_64
          target: aosp_atd
        - api-level: 34
          arch: x86
          target: android-tv
name: Build
on:
  repository_dispatch:
    types: trigger-ga___android.yml
