jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.maven_ossrhPassword }}
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.maven_ossrhUsername }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword
          }}
      name: Build with Gradle
      run: ./gradlew publish
name: Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
